/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crownCrowdsaleSol from "./CrownCrowdsale.sol";
export type { crownCrowdsaleSol };
import type * as heroSol from "./Hero.sol";
export type { heroSol };
export type { CrownToken } from "./CrownToken";
export type { CrownVault } from "./CrownVault";
export type { HeroMarketplace } from "./HeroMarketplace";
export type { USDT } from "./USDT";
