/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crownCrowdsaleSol from "./CrownCrowdsale.sol";
export type { crownCrowdsaleSol };
export type { CrownToken } from "./CrownToken";
export type { CrownVault } from "./CrownVault";
export type { USDT } from "./USDT";
